name: artifacts

on: push

env:
  my_file: 'deepak'

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch ${{env.my_file}}.txt
          echo "My name is D" >> ${{env.my_file}}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{env.my_file}}.txt
      - run: |
          rm ${{env.my_file}}.txt
          ls -al

  download-artifacts:
    needs: [upload-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./
      - run: |
          ls -al
          cat ${{env.my_file}}.txt
          