name: checkout-with-args

on: push

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repo
      uses: actions/checkout@v2
      run: |
        ls -ltr
        java --version

    - name: checkout tomcat
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat
        ref: master
        path: ./tomcat
    - name: install java 
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        java-package: jdk
        architecture: x64
    - name: fina list
      run: |
        touch tomcat-configs.xml
        cp tomcat-configs.xml tomcat/
        ls -ltr
        java --version
        
